fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: MTAyMC8yNzMyNC8zOTAy
## 来必力(data-uid)
gentie: ## Your gentie_productKey, e.g. fc799538c7ad4cf5a5a0c2877a90cbd7
google_search: false ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-100099282-1 
## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: 链接
    directory: links/
    icon: fa-link
  - page: 星空语录
    directory: quotations/
    icon: fa-heart
  - page: rss
    directory: atom.xml
    icon: fa-rss
    
hide_post_sidebar: true

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - bookmarks
  - category
  - tag
  - recent_posts
  - recent_comments
  - links
## Social Icons
social_icons:
  - ['/images/github.png', 'https://github.com/jerry011235']
  - ['/images/zhihu.png', 'https://www.zhihu.com/people/istarsky/answers']
  - ['/images/jianshu.png', 'http://www.jianshu.com/u/e2bf41f8a517']
  - ['/images/weibo.png', 'http://weibo.com/istarsky']

links:
  - title: site-name1
    url: http://www.example1.com/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/
    
bookmarks:
  - title: github博客
    url: http://jerry011235.github.io/
  - title: 222
    url: http://starwindy.oschina.io/

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 0.0.0
